spring.application.name=server

# -----------------------
# MongoDB Configuration
# -----------------------
server.port=8081
# ✅ MongoDB Atlas connection (for production or cloud use)
# spring.data.mongodb.uri=mongodb+srv://admin:password123@cluster0.abcd.mongodb.net/mydatabase?retryWrites=true&w=majority

# ✅ Optional: Local MongoDB fallback (for development)
 spring.data.mongodb.uri=mongodb://localhost:27017/fooddb
#spring.data.mongodb.uri=mongodb://host.docker.internal:27017/fooddb
#spring.data.mongodb.uri=mongodb+srv://sudipbasakk1234_db_user:7NlwVErBScdIxLJD@cluster0.3qxjeg5.mongodb.net/fooddb?appName=Cluster0

#  jwt.secret=my_super_secret_key_12345
# jwt.expiration=86400000

razorpay.key.id=rzp_test_RXJG1b108YPqAs
razorpay.key.secret=AOtgA4jfunbtJivEBwmCgCP5





# Kafka Broker URL (your local broker)
# spring.kafka.bootstrap-servers=localhost:9092

# Producer settings
# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer settings
# spring.kafka.consumer.group-id=my-group
# spring.kafka.consumer.auto-offset-reset=earliest
# spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer



# 7NlwVErBScdIxLJD         sudipbasakk1234_db_user